apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-mongo
spec:
  replicas: {{ .Values.mongo.replicas }}
  selector:
    matchLabels:
      app: library-mongo
  template:
    metadata:
      labels:
        app: library-mongo
    spec:
      containers:
        - name: library-mongo
          image: mongo:4.4.2
          {{- if not (eq .Values.global.env "development") }}
          volumeMounts:
          - mountPath: /data/db
            name: mongo-storage
          {{- end }}
          envFrom:
            - secretRef:
                name: library-mongo-secret
      {{- if not (eq .Values.global.env "development") }}
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: library-mongo-pvc
      {{- end }}
