global:
  env: "development"

namespace: murm-logging

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
  resources:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 2
      memory: 4Gi

kibana:
  image: docker.elastic.co/kibana/kibana:8.12.1
  resources:
    requests:
      cpu: 1
      memory: 500Mi
    limits:
      cpu: 2
      memory: 1Gi
