apiVersion: v1
kind: ConfigMap
metadata:
  name: index-config
data:
  SERVER_PORT: "8080"
  SERVER_TIMEOUT_READ: 5s
  SERVER_TIMEOUT_WRITE: 10s
  SERVER_TIMEOUT_IDLE: 15s
  MONGO_URI: mongodb://index-mongo:27017
  MONGO_DB_NAME: murmurations
  ELASTICSEARCH_URL: http://index-es:9200
  NATS_CLUSTER_ID: murmurations
  NATS_URL: http://nats:4222
