apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "murmurations.index" . }}
spec:
  replicas: {{ .Values.index.replicas }}
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
        - name: index
          image: {{ .Values.indexServiceImage }}
          volumeMounts:
            - mountPath: /src/index
              name: source-path
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: index-config
      volumes:
        - name: source-path
          hostPath:
            path: {{ .Values.sourcepath }}
