controller:
  config:
    use-proxy-protocol: "true"
    use-forwarded-headers: "true"
  service:
    annotations:
      service.beta.kubernetes.io/do-loadbalancer-enable-proxy-protocol: "true"
      # See: proxy_protocol mode breaks HTTP01 challenge Check stage
      # https://github.com/jetstack/cert-manager/issues/466
      # Specifies the hostname used for the Service status.Hostname instead of assigning status.IP directly.
      # e.g. "index.murmurations.network", "test-index.murmurations.network"
      service.beta.kubernetes.io/do-loadbalancer-hostname: <DO-LOADBALANCER-HOSTNAME>
    externalTrafficPolicy: "Cluster"
