apiVersion: v1
kind: Service
metadata:
  name: profile-mongo
spec:
  selector:
    app: profile-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: {{ .Values.mongo.service.port }}
