# linters-settings: This section is used to configure individual linters.
linters-settings:
  # gofmt: Configuration for the gofmt linter.
  gofmt:
    # simplify: Simplify code when possible.
    simplify: true
  # misspell: Configuration for the misspell linter.
  misspell:
    # locale: Set the locale to US to catch US-specific spelling mistakes.
    locale: US

# run: This section is used to configure how golangci-lint runs.
run:
  # timeout: Set a timeout of 5 minutes.
  timeout: 5m
  # skip-dirs: Skip the specified directories.
  skip-dirs:
    - vendor

# issues: This section is used to configure how golangci-lint handles issues.
issues:
  # exclude-rules: Exclude the specified rules.
  exclude-rules:
    # Each rule is a dictionary with a linters list and a text string.
    - linters:
        # linters: The rule applies to these linters.
        - staticcheck
      # text: Ignore using a deprecated function, variable, constant or field.
      text: "SA1019"
