apiVersion: skaffold/v2beta6
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: murmurations/indexer
      context: .
      docker:
        dockerfile: services/indexer/docker/Dockerfile-dev
      sync:
        manual:
          - src: 'services/indexer/**/*.go'
            dest: .
