apiVersion: skaffold/v2beta9
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: murmurations/index
      context: .
      docker:
        dockerfile: services/index/docker/Dockerfile-dev
    - image: murmurations/validation
      context: .
      docker:
        dockerfile: services/validation/docker/Dockerfile-dev
deploy:
  helm:
    releases:
    - name: development
      chartPath: murmurations
      artifactOverrides:
        indexServiceImage: murmurations/index
        validationServiceImage: murmurations/validation
      # Skaffold will try to parse the value part of each key-value pair using environment variables in the system
      setValueTemplates:
        sourcepath: "{{.SOURCEPAH}}"
