apiVersion: skaffold/v2beta9
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: murmurations/index
      context: .
      docker:
        dockerfile: services/index/docker/Dockerfile-dev
    - image: murmurations/validation
      context: .
      docker:
        dockerfile: services/validation/docker/Dockerfile-dev
    - image: murmurations/library
      context: .
      docker:
        dockerfile: services/library/docker/Dockerfile-dev
    - image: murmurations/nodecleanup
      context: .
      docker:
        dockerfile: services/cronjob/nodecleanup/docker/Dockerfile-dev
    - image: murmurations/parseschema
      context: .
      docker:
        dockerfile: services/cronjob/parseschema/docker/Dockerfile-dev
deploy:
  helm:
    releases:
    - name: development
      chartPath: charts/murmurations
      artifactOverrides:
        indexServiceImage: murmurations/index
        validationServiceImage: murmurations/validation
        libraryServiceImage: murmurations/library
        # cronjobs
        nodecleanupImage: murmurations/nodecleanup
        parseschemaImage: murmurations/parseschema
      # Skaffold will try to parse the value part of each key-value pair using environment variables in the system
      setValueTemplates:
        sourcepath: "{{.SOURCEPATH}}"
