apiVersion: skaffold/v4beta5
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: murmurations/dataproxy
      context: .
      docker:
        dockerfile: build/dataproxy/docker/Dockerfile-dev
    - image: murmurations/dataproxyrefresher
      context: .
      docker:
        dockerfile: build/dataproxyrefresher/docker/Dockerfile-dev
    - image: murmurations/dataproxyupdater
      context: .
      docker:
        dockerfile: build/dataproxyupdater/docker/Dockerfile-dev
    - image: murmurations/geoip
      context: .
      docker:
        dockerfile: build/geoip/docker/Dockerfile-dev
    - image: murmurations/index
      context: .
      docker:
        dockerfile: build/index/docker/Dockerfile-dev
    - image: murmurations/library
      context: .
      docker:
        dockerfile: build/library/docker/Dockerfile-dev
    - image: murmurations/nodecleaner
      context: .
      docker:
        dockerfile: build/nodecleaner/docker/Dockerfile-dev
    - image: murmurations/revalidatenode
      context: .
      docker:
        dockerfile: build/revalidatenode/docker/Dockerfile-dev
    - image: murmurations/schemaparser
      context: .
      docker:
        dockerfile: build/schemaparser/docker/Dockerfile-dev
    - image: murmurations/validation
      context: .
      docker:
        dockerfile: build/validation/docker/Dockerfile-dev
deploy:
  # Deadline for deployments to stabilize in seconds.
  statusCheckDeadlineSeconds: 300
  helm:
    releases:
    - name: development
      chartPath: charts/murmurations
      setValueTemplates:
        # Using setValueTemplates to set image references dynamically.
        # https://skaffold-v2-latest.firebaseapp.com/docs/deployers/helm/#fqn-strategy-single-fully-qualified-name-default
        index.image: "{{.IMAGE_FULLY_QUALIFIED_murmurations_index}}"
        validation.image: "{{.IMAGE_FULLY_QUALIFIED_murmurations_validation}}"
        library.image: "{{.IMAGE_FULLY_QUALIFIED_murmurations_library}}"
        nodecleaner.image: "{{.IMAGE_FULLY_QUALIFIED_murmurations_nodecleaner}}"
        schemaparser.image: "{{.IMAGE_FULLY_QUALIFIED_murmurations_schemaparser}}"
        revalidatenode.image: "{{.IMAGE_FULLY_QUALIFIED_murmurations_revalidatenode}}"
        geoip.image: "{{.IMAGE_FULLY_QUALIFIED_murmurations_geoip}}"
        dataproxy.image: "{{.IMAGE_FULLY_QUALIFIED_murmurations_dataproxy}}"
        dataproxyupdater.image: "{{.IMAGE_FULLY_QUALIFIED_murmurations_dataproxyupdater}}"
        dataproxyrefresher.image: "{{.IMAGE_FULLY_QUALIFIED_murmurations_dataproxyrefresher}}"
        # SOURCEPATH is provided by the environment variable. It is the location of the MurmurationsServices
        # on your local computer.
        global.sourcepath: "{{.SOURCEPATH}}"
        global.env: "development"
portForward:
  - resourceType: service
    resourceName: index-mongo
    namespace: default
    port: 27017
    localPort: 27017
  - resourceType: service
    resourceName: library-mongo
    namespace: default
    port: 27017
    localPort: 27018
  - resourceType: service
    resourceName: data-proxy-mongo
    namespace: default
    port: 27017
    localPort: 27019
