apiVersion: skaffold/v2beta6
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/development/*
build:
  local:
    push: false
  artifacts:
    - image: murmurations/index
      context: .
      docker:
        dockerfile: services/index/docker/Dockerfile-dev
    - image: murmurations/validation
      context: .
      docker:
        dockerfile: services/validation/docker/Dockerfile-dev
