apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: index-es-cluster
spec:
  serviceName: index-es
  replicas: {{ .Values.indexES.replicas }}
  selector:
    matchLabels:
      app: index-es
  template:
    metadata:
      labels:
        app: index-es
    spec:
      containers:
        - name: index-es
          image: 'docker.elastic.co/elasticsearch/elasticsearch:7.9.3'
          resources:
            requests:
              memory: "1Gi"
              cpu: "32m"
            limits:
              memory: "2Gi"
              cpu: "64m"
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: index-es-config
      initContainers:
        - name: increase-vm-max-map
          image: busybox
          command:
            - sysctl
            - '-w'
            - vm.max_map_count=262144
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command:
            - sh
            - '-c'
            - ulimit -n 65536
          securityContext:
            privileged: true
