{{- if not (eq .Values.global.env "development") }}
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kube-logging
spec:
  selector:
    app: kibana
  ports:
    - name: http
      port: 5601
{{- end }}
