apiVersion: v1
kind: ConfigMap
metadata:
  name: index-es-config
data:
  cluster.name: index-service-es
  discovery.seed_hosts: "index-es-cluster-0.index-es,index-es-cluster-1.index-es,index-es-cluster-2.index-es"
  cluster.initial_master_nodes: "index-es-cluster-0,index-es-cluster-1,index-es-cluster-2"
  ES_JAVA_OPTS: "-Xms512m -Xmx512m"
  xpack.security.enabled: "false"
