{{- $env := .Values.global.env }}
{{- $isProd := eq $env "production" }}
{{- $isStaging := eq $env "staging" }}
{{- $isPretest := eq $env "pretest" }}
{{- $isDev := eq $env "development" }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: nodecleaner-app
spec:
  {{- if eq .Values.global.env "production" }}
  schedule: "0 */12 * * *" # every 12 hours
  {{- else }}
  schedule: "*/2 * * * *"  # every 2 minutes
  {{- end }}
  # Keep the latest successful job.
  successfulJobsHistoryLimit: 1
  # Keep the latest failed job.
  failedJobsHistoryLimit: 1
  # Only one instance of the job is running at any given time.
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 10
      # Retry the Job 3 times before marking it as failed.
      backoffLimit: 3
      # Delete the Job and its pods 24 hours after completion.
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            log-group: murm
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/nodecleaner/config.yaml") . | sha256sum }}
        spec:
          containers:
            - name: nodecleaner-app
              image: {{ .Values.image }}
              imagePullPolicy: IfNotPresent
              {{- if not $isDev }}
              resources:
                limits:
                  cpu: "500m"
                requests:
                  cpu: "100m"
              {{- end }}
              envFrom:
                - configMapRef:
                    name: nodecleaner-app-config
                - secretRef:
                    name: nodecleaner-secret
          {{- if $isDev }}
              command: ["go", "run"]
              args: ["cmd/nodecleaner/main.go"]
              volumeMounts:
                - mountPath: /src
                  name: source-path
          volumes:
            - name: source-path
              hostPath:
                path: {{ .Values.global.sourcepath }}
          {{- end }}
          restartPolicy: Never
