apiVersion: batch/v1
kind: CronJob
metadata:
  name: nodecleaner-app
spec:
  {{- if or (eq .Values.global.env "main") (eq .Values.global.env "production") }}
  schedule: "0 */12 * * *" # every 12 hours
  {{- else if or (eq .Values.global.env "staging") (eq .Values.global.env "pretest") }}
  schedule: "*/2 * * * *"  # every 2 minutes
  {{- else }}
  schedule: "*/2 * * * *"  # every 2 minutes
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/nodecleaner/config.yaml") . | sha256sum }}
        spec:
          containers:
            - name: nodecleaner-app
              image: {{ .Values.image }}
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: nodecleaner-app-config
                - secretRef:
                    name: nodecleaner-secret
          {{- if eq .Values.global.env "development" }}
              command: ["go", "run"]
              args: ["services/cronjob/nodecleaner/cmd/nodecleaner/main.go"]
              volumeMounts:
                - mountPath: /src
                  name: source-path
          volumes:
            - name: source-path
              hostPath:
                path: {{ .Values.global.sourcepath }}
          {{- end }}
          restartPolicy: Never
