{{- $env := .Values.global.env }}
{{- $isLive := eq $env "live" }}
{{- $isLiveTest := eq $env "live-test" }}
{{- $isCI := eq $env "ci" }}
{{- $isDev := eq $env "dev" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: data-proxy-app-config
data:
  SERVER_PORT: "8080"
  SERVER_TIMEOUT_READ: "5s"
  SERVER_TIMEOUT_WRITE: "10s"
  SERVER_TIMEOUT_IDLE: "15s"
  MONGO_HOST: "data-proxy-mongo:27017"
  MONGO_DB_NAME: "murmurationsDataProxy"
  INDEX_HOST: "http://index-app:8080"
  LIBRARY_URL: "http://library-app:8080"
  GET_RATE_LIMIT_PERIOD: "6000-M"
  POST_RATE_LIMIT_PERIOD: "6000-M"
  EXTERNAL_DATA_PROXY_URL:
    {{- if $isLive }}
    "https://data-proxy.murmurations.network"
    {{- else if $isLiveTest }}
    "https://test-data-proxy.murmurations.network"
    {{- else if $isCI }}
    "https://pretest1-data-proxy.murmurations.network"
    {{- else }}
    "http://data-proxy-app:8080"
    {{- end }}
