apiVersion: v1
kind: ConfigMap
metadata:
  name: data-proxy-app-config
data:
  SERVER_PORT: "8080"
  SERVER_TIMEOUT_READ: 5s
  SERVER_TIMEOUT_WRITE: 10s
  SERVER_TIMEOUT_IDLE: 15s
  MONGO_HOST: data-proxy-mongo:27017
  MONGO_DB_NAME: murmurationsDataProxy
  INDEX_HOST: http://index-app:8080
  LIBRARY_URL: http://library-app:8080
  GET_RATE_LIMIT_PERIOD: 6000-M
  POST_RATE_LIMIT_PERIOD: 6000-M
  {{- if eq .Values.global.env "production" }}
  EXTERNAL_DATA_PROXY_URL: https://data-proxy.murmurations.network
  {{- else if eq .Values.global.env "staging" }}
  EXTERNAL_DATA_PROXY_URL: https://test-data-proxy.murmurations.network
  {{- else }}
  EXTERNAL_DATA_PROXY_URL: http://data-proxy-app:8080
  {{- end }}
