apiVersion: apps/v1
kind: Deployment
metadata:
  name: murmurations-library
spec:
  replicas: {{ .Values.library.replicas }}
  selector:
    matchLabels:
      app: library
  template:
    metadata:
      labels:
        app: library
    spec:
      containers:
        - name: library
          image: {{ .Values.libraryServiceImage }}
          volumeMounts:
            - mountPath: /src/library
              name: source-path
          envFrom:
            - configMapRef:
                name: library-config
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 35
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: source-path
          hostPath:
            path: {{ .Values.sourcepath }}
