apiVersion: v1
kind: Service
metadata:
  name: {{ template "murmurations.library" . }}
spec:
  selector:
    app: library
  ports:
    - name: library
      protocol: TCP
      port: {{ .Values.library.service.port }}
