apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index-mongo
  template:
    metadata:
      labels:
        app: index-mongo
    spec:
      containers:
        - name: index-mongo
          image: mongo
---
apiVersion: v1
kind: Service
metadata:
  name: index-mongo
spec:
  selector:
    app: index-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
