apiVersion: v1
kind: ConfigMap
metadata:
  name: schemaparser-config
data:
  MONGO_HOST: library-mongo:27017
  MONGO_DB_NAME: murmurationsLibrary
  LIBRARY_CDN_URL: https://cdn.murmurations.tech
  REDIS_URL: schemaparser-redis:6379
