apiVersion: v1
kind: ConfigMap
metadata:
  name: schemaparser-app-config
data:
  MONGO_HOST: library-mongo:27017
  MONGO_DB_NAME: murmurationsLibrary
  {{- if eq .Values.global.env "production" }}
  LIBRARY_CDN_URL: https://cdn.murmurations.network
  {{- else if eq .Values.global.env "staging" }}
  LIBRARY_CDN_URL: https://test-cdn.murmurations.network
  {{-end }}
  REDIS_URL: schemaparser-redis:6379
