apiVersion: v1
kind: ConfigMap
metadata:
  name: schemaparser-app-config
data:
  MONGO_HOST: library-mongo:27017
  MONGO_DB_NAME: murmurationsLibrary
  {{- if eq .Values.global.env "production" }}
  LIBRARY_URL: https://library.murmurations.network
  {{- else }}
  LIBRARY_URL: https://test-library.murmurations.network
  {{- end }}
  {{- if eq .Values.global.env "production" }}
  GITHUB_BRANCH_URL: https://api.github.com/repos/MurmurationsNetwork/MurmurationsLibrary/branches/main
  {{- else }}
  GITHUB_BRANCH_URL: https://api.github.com/repos/MurmurationsNetwork/MurmurationsLibrary/branches/test
  {{- end }}
  GITHUB_TREE_URL: https://api.github.com/repos/MurmurationsNetwork/MurmurationsLibrary/git/trees
  REDIS_URL: schemaparser-redis:6379
  {{- if eq .Values.global.env "development" }}
  IS_LOCAL: "true"
  {{- else }}
  IS_LOCAL: "false"
  {{- end }}
