{{- $env := .Values.global.env }}
{{- $isLive := eq $env "live" }}
{{- $isLiveTest := eq $env "live-test" }}
{{- $isCI := eq $env "ci" }}
{{- $isDev := eq $env "dev" }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: schemaparser-app-config
data:
  MONGO_HOST: library-mongo:27017
  MONGO_DB_NAME: murmurationsLibrary
  {{- if $isLive }}
  LIBRARY_URL: https://library.murmurations.network
  {{- else }}
  LIBRARY_URL: https://test-library.murmurations.network
  {{- end }}
  {{- if $isLive }}
  GITHUB_BRANCH_URL: https://api.github.com/repos/MurmurationsNetwork/MurmurationsLibrary/branches/main
  {{- else }}
  GITHUB_BRANCH_URL: https://api.github.com/repos/MurmurationsNetwork/MurmurationsLibrary/branches/test
  {{- end }}
  GITHUB_TREE_URL: https://api.github.com/repos/MurmurationsNetwork/MurmurationsLibrary/git/trees
  REDIS_URL: schemaparser-redis:6379
  {{- if $isDev }}
  IS_LOCAL: "true"
  {{- else }}
  IS_LOCAL: "false"
  {{- end }}
