apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: schemaparser
spec:
  {{- if eq .Values.global.env "development" }}
  schedule: "*/1 * * * *"
  {{- else }}
  schedule: "*/5 * * * *"
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: schemaparser
              image: {{ .Values.image }}
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: schemaparser-config
          {{- if eq .Values.global.env "development" }}
              command: ["go", "run"]
              args: ["services/cronjob/schemaparser/cmd/schemaparser/main.go"]
              volumeMounts:
                - mountPath: /src
                  name: source-path
          volumes:
            - name: source-path
              hostPath:
                path: {{ .Values.global.sourcepath }}
          {{- end }}
          restartPolicy: Never
