apiVersion: batch/v1
kind: CronJob
metadata:
  name: schemaparser-app
spec:
  {{- if or (eq .Values.global.env "live") (eq .Values.global.env "production") }}
  schedule: "*/1 * * * *"  # every minute
  {{- else if or (eq .Values.global.env "staging") (eq .Values.global.env "pretest") }}
  schedule: "*/1 * * * *"  # every minute
  {{- else }}
  schedule: "*/2 * * * *"  # every two minutes
  {{- end }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/schemaparser/config.yaml") . | sha256sum }}
        spec:
          containers:
            - name: schemaparser-app
              image: {{ .Values.image }}
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: schemaparser-app-config
                - secretRef:
                    name: schemaparser-secret
          {{- if eq .Values.global.env "development" }}
              command: ["go", "run"]
              args: ["services/cronjob/schemaparser/cmd/schemaparser/main.go"]
              volumeMounts:
                - mountPath: /src
                  name: source-path
          volumes:
            - name: source-path
              hostPath:
                path: {{ .Values.global.sourcepath }}
          {{- end }}
          restartPolicy: Never
