apiVersion: v1
kind: ConfigMap
metadata:
  name: index-app-config
data:
  SERVER_PORT: "8080"
  SERVER_TIMEOUT_READ: 5s
  SERVER_TIMEOUT_WRITE: 10s
  SERVER_TIMEOUT_IDLE: 15s
  MONGO_HOST: index-mongo:27017
  MONGO_DB_NAME: murmurationsIndex
  ELASTICSEARCH_URL: http://index-es:9200
  NATS_CLUSTER_ID: murmurations
  NATS_URL: http://nats:4222
  {{- if or (eq .Values.global.env "production") (eq .Values.global.env "staging") (eq .Values.global.env "pretest") }}
  TAGS_ARRAY_SIZE: "100"
  TAGS_STRING_LENGTH: "100"
  {{- else }}
  TAGS_ARRAY_SIZE: "5"
  TAGS_STRING_LENGTH: "10"
  {{- end }}
  TAGS_FUZZINESS: "3"
  # Rate limit
  GET_RATE_LIMIT_PERIOD: 60-M
  {{- if eq .Values.global.env "production" }}
  POST_RATE_LIMIT_PERIOD: 6-M
  {{- else }}
  POST_RATE_LIMIT_PERIOD: 60-M
  {{- end }}
