{{- $env := .Values.global.env }}
{{- $isProd := eq $env "production" }}
{{- $isStaging := eq $env "staging" }}
{{- $isPretest := eq $env "pretest" }}
{{- $isDev := eq $env "development" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-app
spec:
  # Limit old ReplicaSets to reduce clutter. 0 means only keep the current one.
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: index-app
  template:
    metadata:
      labels:
        app: index-app
        log-group: murm
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/index/config.yaml") . | sha256sum }}
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      containers:
        - name: index-app
          image: {{ .Values.image }}
          {{- if not $isDev }}
          # Resources configuration only for non-development environments
          resources:
            requests:
              memory: "128Mi"
              cpu: "32m"
            limits:
              memory: "256Mi"
              cpu: "256m"
          {{- end }}
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: index-app-config
            - secretRef:
                name: index-secret
          livenessProbe:
            httpGet:
              path: v2/ping
              port: {{ .Values.index.service.port }}
            initialDelaySeconds: 120
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 4
      {{- if eq .Values.global.env "development" }}
          volumeMounts:
            - mountPath: /src/index
              name: source-path
      volumes:
        - name: source-path
          hostPath:
            path: {{ .Values.global.sourcepath }}
      {{- end }}
