apiVersion: v1
kind: ConfigMap
metadata:
  name: library-app-config
data:
  SERVER_PORT: "8080"
  SERVER_TIMEOUT_READ: 5s
  SERVER_TIMEOUT_WRITE: 10s
  SERVER_TIMEOUT_IDLE: 15s
  MONGO_HOST: library-mongo:27017
  MONGO_DB_NAME: murmurationsLibrary
  # Rate limit
  {{- if or (eq .Values.global.env "live") (eq .Values.global.env "production") }}
  GET_RATE_LIMIT_PERIOD: 600-M
  POST_RATE_LIMIT_PERIOD: 600-M
  {{- else }}
  GET_RATE_LIMIT_PERIOD: 6000-M
  POST_RATE_LIMIT_PERIOD: 6000-M
  {{- end }}
