{{- $env := .Values.global.env }}
{{- $isProd := eq $env "production" }}
{{- $isStaging := eq $env "staging" }}
{{- $isMurmproto := eq $env "murmproto" }}
{{- $isDev := eq $env "development" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app
spec:
  # Limit old ReplicaSets to reduce clutter. 0 means only keep the current one.
  revisionHistoryLimit: 0
  replicas: {{ .Values.library.replicas }}
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/library/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: library-app
          image: {{ .Values.image }}
          {{- if $isMurmproto }}
          resources:
            requests:
              memory: "32Mi"
            limits:
              memory: "64Mi"
          {{- end }}
          envFrom:
            - configMapRef:
                name: library-app-config
            - secretRef:
                name: library-secret
          livenessProbe:
            httpGet:
              path: v2/ping
              port: 8080
            initialDelaySeconds: 600
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 3
      {{- if $isDev }}
          volumeMounts:
            - mountPath: /src/library
              name: source-path
      volumes:
        - name: source-path
          hostPath:
            path: {{ .Values.global.sourcepath }}
      {{- end }}

---

{{- if $isMurmproto }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: library-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
{{- end }}
