apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app
spec:
  replicas: {{ .Values.library.replicas }}
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
    spec:
      containers:
        - name: library-app
          image: {{ .Values.image }}
          resources:
            requests:
              memory: "32Mi"
              cpu: "8m"
            limits:
              memory: "64Mi"
              cpu: "16m"
          envFrom:
            - configMapRef:
                name: library-app-config
            - secretRef:
                name: library-secret
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 35
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      {{- if eq .Values.global.env "development" }}
          volumeMounts:
            - mountPath: /src/library
              name: source-path
      volumes:
        - name: source-path
          hostPath:
            path: {{ .Values.global.sourcepath }}
      {{- end }}
