apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-app
spec:
  replicas: {{ .Values.library.replicas }}
  selector:
    matchLabels:
      app: library-app
  template:
    metadata:
      labels:
        app: library-app
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/library/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: library-app
          image: {{ .Values.image }}
          # resources:
          #   requests:
          #     memory: "32Mi"
          #     cpu: "8m"
          #   limits:
          #     memory: "64Mi"
          #     cpu: "16m"
          envFrom:
            - configMapRef:
                name: library-app-config
            - secretRef:
                name: library-secret
          livenessProbe:
            httpGet:
              path: v1/ping
              port: 8080
            initialDelaySeconds: 600
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 3
      {{- if eq .Values.global.env "development" }}
          volumeMounts:
            - mountPath: /src/library
              name: source-path
      volumes:
        - name: source-path
          hostPath:
            path: {{ .Values.global.sourcepath }}
      {{- end }}
