apiVersion: batch/v1
kind: CronJob
metadata:
  name: dataproxyrefresher-app
spec:
  {{- if eq .Values.global.env "production" }}
  schedule: "0 1 * * *" # every day at 1 a.m.
  {{- else if or (eq .Values.global.env "staging") }}
  schedule: "0 * * * *" # every hour
  {{- else }}
  schedule: "*/2 * * * *"  # every 2 minutes
  {{- end }}
  # Keep the latest successful job.
  successfulJobsHistoryLimit: 1
  # Keep the latest failed job.
  failedJobsHistoryLimit: 1
  # Only one instance of the job is running at any given time.
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      # Retry the Job 3 times before marking it as failed.
      backoffLimit: 3
      # Delete the Job and its pods 24 hours after completion.
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/dataproxyrefresher/config.yaml") . | sha256sum }}
        spec:
          containers:
            - name: dataproxyrefresher-app
              image: {{ .Values.image }}
              imagePullPolicy: IfNotPresent
              # Limit the CPU usage.
              resources:
                limits:
                  cpu: "500m"
                requests:
                  cpu: "100m"
              envFrom:
                - configMapRef:
                    name: dataproxyrefresher-app-config
                - secretRef:
                    name: dataproxyrefresher-secret
          {{- if eq .Values.global.env "development" }}
              command: ["go", "run"]
              args: ["services/cronjob/dataproxyrefresher/cmd/dataproxyrefresher/main.go"]
              volumeMounts:
                - mountPath: /src
                  name: source-path
          volumes:
            - name: source-path
              hostPath:
                path: {{ .Values.global.sourcepath }}
          {{- end }}
          restartPolicy: Never
