apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-mongo
spec:
  replicas: {{ .Values.mongo.replicas }}
  selector:
    matchLabels:
      app: index-mongo
  template:
    metadata:
      labels:
        app: index-mongo
    spec:
      containers:
        - name: index-mongo
          image: mongo:4.4.2
