{{- $env := .Values.global.env }}
{{- $isProd := eq $env "production" }}
{{- $isStaging := eq $env "staging" }}
{{- $isMurmproto := eq $env "murmproto" }}
{{- $isDev := eq $env "development" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-mongo
spec:
  # Limit old ReplicaSets to reduce clutter. 0 means only keep the current one.
  revisionHistoryLimit: 0
  replicas: {{ .Values.mongo.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: index-mongo
  template:
    metadata:
      labels:
        app: index-mongo
    spec:
      priorityClassName: murmurations-high-priority
      containers:
        - name: index-mongo
          image: mongo:5.0.6
          # resources:
          #   requests:
          #     memory: "128Mi"
          #     cpu: "8m"
          #   limits:
          #     memory: "256Mi"
          #     cpu: "16m"
          {{- if not $isDev }}
          volumeMounts:
          - mountPath: /data/db
            name: mongo-storage
          {{- end }}
          envFrom:
            - secretRef:
                name: index-mongo-secret
      {{- if not $isDev }}
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: index-mongo-pvc
      {{- end }}

---

{{- if $isMurmproto }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: index-mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: longhorn
{{- end }}
