# Define environment variables to control the deployment configuration.
{{- $env := .Values.global.env }}
{{- $notDev := ne $env "development" }}

{{- if $notDev }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: pod-cleanup-job
  namespace: default
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pod-cleanup-account
          containers:
          - name: cleanup
            image: {{ .Values.image }}
            imagePullPolicy: Always
          restartPolicy: Never
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3

{{- end }}
