apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: schemaparser-redis
  labels:
    app: redis
    role: leader
spec:
  serviceName: "schemaparser-redis"
  replicas: 1
  selector:
    matchLabels:
      app: redis
      role: leader
  template:
    metadata:
      labels:
        app: redis
        role: leader
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      containers:
      - name: leader
        image: redis:7.2.4
        resources:
          requests:
            memory: "16Mi"
            cpu: "8m"
          limits:
            memory: "32Mi"
            cpu: "16m"
        ports:
        - containerPort: 6379
