apiVersion: v1
kind: ConfigMap
metadata:
  name: validation-config
data:
  SERVER_PORT: "8080"
  SERVER_TIMEOUT_READ: 5s
  SERVER_TIMEOUT_WRITE: 10s
  SERVER_TIMEOUT_IDLE: 15s
  NATS_CLUSTER_ID: murmurations
  NATS_URL: http://nats:4222
  LIBRARY_CDN_URL: https://cdn.murmurations.tech
