apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer
  template:
    metadata:
      labels:
        app: indexer
    spec:
      containers:
        - name: indexer
          image: murmurations/indexer
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: indexer-srv
spec:
  selector:
    app: indexer
  ports:
    - name: indexer
      protocol: TCP
      port: 8080
      targetPort: 8080
