apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation
  template:
    metadata:
      labels:
        app: validation
    spec:
      containers:
        - name: validation
          image: murmurations/validation
          resources:
            limits:
              memory: 2Gi
              cpu: 2000m
          env:
            - name: NATS_CLUSTER_ID
              value: murmurations
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats:4222'
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: validation
spec:
  selector:
    app: validation
  ports:
    - name: validation
      protocol: TCP
      port: 8080
