apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation
  template:
    metadata:
      labels:
        app: validation
    spec:
      containers:
        - name: validation
          image: murmurations/validation
          env:
            - name: NATS_CLUSTER_ID
              value: murmurations
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats-svc:4222'
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: validation-svc
spec:
  selector:
    app: validation
  ports:
    - name: validation
      protocol: TCP
      port: 8080
      targetPort: 8080
