apiVersion: batch/v1
kind: CronJob
metadata:
  name: revalidatenode-app
spec:
  {{- if eq .Values.global.env "production" }}
  schedule: "*/1 * * * *"  # every minute
  {{- else if or (eq .Values.global.env "staging") (eq .Values.global.env "pretest") }}
  schedule: "*/1 * * * *"  # every minute
  {{- else }}
  schedule: "*/1 * * * *"  # every minute
  {{- end }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: revalidatenode-app
              image: {{ .Values.image }}
              imagePullPolicy: IfNotPresent
              env:
                - name: NATS_CLIENT_ID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              envFrom:
                - configMapRef:
                    name: revalidatenode-app-config
                - secretRef:
                    name: revalidatenode-secret
          {{- if eq .Values.global.env "development" }}
              command: ["go", "run"]
              args: ["services/cronjob/revalidatenode/cmd/revalidatenode/main.go"]
              volumeMounts:
                - mountPath: /src
                  name: source-path
          volumes:
            - name: source-path
              hostPath:
                path: {{ .Values.global.sourcepath }}
          {{- end }}
          restartPolicy: Never
