{{- $env := .Values.global.env }}
{{- $isProd := eq $env "production" }}
{{- $isStaging := eq $env "staging" }}
{{- $isPretest := eq $env "pretest" }}
{{- $isDev := eq $env "development" }}

apiVersion: batch/v1
kind: CronJob
metadata:
  name: revalidatenode-app
spec:
  {{- if or $isProd $isStaging $isPretest }}
  schedule: "*/1 * * * *"  # every minute
  {{- else }}
  schedule: "*/2 * * * *"  # every two minutes
  {{- end }}
  # Keep the latest successful job.
  successfulJobsHistoryLimit: 1
  # Keep the latest failed job.
  failedJobsHistoryLimit: 1
  # Only one instance of the job is running at any given time.
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      # Retry the Job 3 times before marking it as failed.
      backoffLimit: 3
      # Delete the Job and its pods 24 hours after completion.
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            log-group: murm
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/revalidatenode/config.yaml") . | sha256sum }}
        spec:
          containers:
            - name: revalidatenode-app
              image: {{ .Values.image }}
              imagePullPolicy: IfNotPresent
              {{- if not $isDev }}
              resources:
                requests:
                  cpu: "100m"
                limits:
                  cpu: "500m"
              {{- end }}
              env:
                - name: NATS_CLIENT_ID
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
              envFrom:
                - configMapRef:
                    name: revalidatenode-app-config
                - secretRef:
                    name: revalidatenode-secret
          {{- if eq .Values.global.env "development" }}
              command: ["go", "run"]
              args: ["cmd/revalidatenode/main.go"]
              volumeMounts:
                - mountPath: /src
                  name: source-path
          volumes:
            - name: source-path
              hostPath:
                path: {{ .Values.global.sourcepath }}
          {{- end }}
          restartPolicy: Never
