{{- $env := .Values.global.env }}
{{- $isProd := eq $env "production" }}
{{- $isStaging := eq $env "staging" }}
{{- $isPretest := eq $env "pretest" }}
{{- $isDev := eq $env "development" }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-proxy-mongo
spec:
  serviceName: "data-proxy-mongo"
  {{ if $isDev }}
  replicas: 1
  {{- else }}
  replicas: {{ .Values.mongo.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: data-proxy-mongo
  template:
    metadata:
      labels:
        app: data-proxy-mongo
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
              matchLabels:
                app: data-proxy-mongo
      containers:
      - name: data-proxy-mongo
        image: mongo:5.0.6
        {{ if or $isProd $isStaging }}
        command: [ "mongod" ]
        args: [ "--config", "/etc/mongo/mongodb.conf" ]
        {{- else }}
        envFrom:
          - secretRef:
              name: data-proxy-mongo-secret
        {{- end }}
        volumeMounts:
        {{- if not $isDev }}
        - name: dataproxy-mongo-storage
          mountPath: /data/db
        {{- end }}
        - name: data-proxy-mongo-config-volume
          mountPath: /etc/mongo
      volumes:
        - name: data-proxy-mongo-config-volume
          configMap:
            name: data-proxy-mongo-config
  {{- if not $isDev }}
  volumeClaimTemplates:
  - metadata:
      name: dataproxy-mongo-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: longhorn
  {{- end }}
