apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-proxy-mongo-pvc
  labels:
    app: data-proxy-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
