{{- $env := .Values.global.env }}
{{- $isLive := eq $env "live" }}
{{- $isLiveTest := eq $env "live-test" }}
{{- $isCI := eq $env "ci" }}
{{- $isDev := eq $env "dev" }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- if or $isLive $isLiveTest $isCI }}
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if $isLive }}
  tls:
  - hosts:
    - index.murmurations.network
    - library.murmurations.network
    - data-proxy.murmurations.network
    secretName: letsencrypt-prod-cert
  {{- end }}
  {{- if $isLiveTest }}
  tls:
  - hosts:
    - test-index.murmurations.network
    - test-library.murmurations.network
    - test-data-proxy.murmurations.network
    secretName: letsencrypt-prod-cert
  {{- end }}
  {{- if $isCI }}
  tls:
  - hosts:
    - pretest1-index.murmurations.network
    - pretest1-library.murmurations.network
    - pretest1-data-proxy.murmurations.network
    secretName: letsencrypt-prod-cert
  {{- end }}
  rules:
    {{- if $isLive }}
    - host: index.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: index-app
                port:
                  number: 8080
    - host: library.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: library-app
                port:
                  number: 8080
    - host: data-proxy.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: data-proxy-app
                port:
                  number: 8080
    {{- else if $isLiveTest }}
    - host: test-index.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: index-app
                port:
                  number: 8080
    - host: test-library.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: library-app
                port:
                  number: 8080
    - host: test-data-proxy.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: data-proxy-app
                port:
                  number: 8080
    {{- else if $isCI }}
    - host: pretest1-index.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: index-app
                port:
                  number: 8080
    - host: pretest1-library.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: library-app
                port:
                  number: 8080
    - host: pretest1-data-proxy.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: data-proxy-app
                port:
                  number: 8080
   {{- else if $isDev }}
    - host: index.murmurations.dev
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: index-app
                port:
                  number: 8080
    - host: library.murmurations.dev
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: library-app
                port:
                  number: 8080
    - host: data-proxy.murmurations.dev
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: data-proxy-app
                port:
                  number: 8080
    {{- end }}
