{{- $env := .Values.global.env }}
{{- $isProd := eq $env "production" }}
{{- $isStaging := eq $env "staging" }}
{{- $isPretest := eq $env "pretest" }}
{{- $isDev := eq $env "development" }}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- if or $isProd $isStaging $isPretest }}
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    {{- end }}
spec:
  ingressClassName: nginx
  {{- if $isPretest }}
  tls:
  - hosts:
    - pretest1-index.murmurations.network
    - pretest1-library.murmurations.network
    - pretest1-data-proxy.murmurations.network
    secretName: letsencrypt-prod-cert
  {{- end }}
  rules:
    {{- if $isProd }}
    - host: index.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: index-app
                port:
                  number: 8080
    - host: library.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: library-app
                port:
                  number: 8080
    - host: data-proxy.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: data-proxy-app
                port:
                  number: 8080
    {{- else if $isStaging }}
    - host: test-index.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: index-app
                port:
                  number: 8080
    - host: test-library.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: library-app
                port:
                  number: 8080
    - host: test-data-proxy.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: data-proxy-app
                port:
                  number: 8080
    {{- else if $isPretest }}
    - host: pretest1-index.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: index-app
                port:
                  number: 8080
    - host: pretest1-library.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: library-app
                port:
                  number: 8080
    - host: pretest1-data-proxy.murmurations.network
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: data-proxy-app
                port:
                  number: 8080
   {{- else if $isDev }}
    - host: index.murmurations.dev
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: index-app
                port:
                  number: 8080
    - host: library.murmurations.dev
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: library-app
                port:
                  number: 8080
    - host: data-proxy.murmurations.dev
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: data-proxy-app
                port:
                  number: 8080
    {{- end }}

---

{{- if or $isProd $isStaging }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: kube-monitoring
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  {{- if $isProd }}
  tls:
    - hosts:
      - monitoring.murmurations.network
      secretName: murmurations-network-tls
  {{- else if $isStaging }}
  tls:
    - hosts:
      - test-monitoring.murmurations.network
      secretName: murmurations-tech-tls
  {{- end }}
  rules:
    {{- if $isProd }}
    - host: monitoring.murmurations.network
    {{- else if $isStaging }}
    - host: test-monitoring.murmurations.network
    {{- end }}
      http:
        paths:
          - pathType: ImplementationSpecific
            path: /(|$)(.*)
            backend:
              service:
                name: kube-prom-stack-grafana
                port:
                  number: 80
{{- end }}
