apiVersion: v1
kind: Service
metadata:
  name: index-es
spec:
  selector:
    app: index-es
  # Headless service
  clusterIP: None
  ports:
    - name: rest
      protocol: TCP
      port: 9200
    - name: inter-node
      protocol: TCP
      port: 9300
