apiVersion: v1
kind: ConfigMap
metadata:
  name: dataproxyupdater-app-config
data:
  MONGO_HOST: data-proxy-mongo:27017
  MONGO_DB_NAME: murmurationsDataProxy
  INDEX_HOST: http://index-app:8080
  {{- if eq .Values.global.env "live" }}
  EXTERNAL_DATA_PROXY_URL: https://main-data-proxy.murmurations.network
  {{- else if eq .Values.global.env "production" }}
  EXTERNAL_DATA_PROXY_URL: https://data-proxy.murmurations.network
  {{- else if eq .Values.global.env "staging" }}
  EXTERNAL_DATA_PROXY_URL: https://test-data-proxy.murmurations.network
  {{- else if eq .Values.global.env "pretest" }}
  EXTERNAL_DATA_PROXY_URL: https://pretest-data-proxy.murmurations.network
  {{- else }}
  EXTERNAL_DATA_PROXY_URL: http://data-proxy-app:8080
  {{- end }}
