apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: index-mongo-pvc-restore
spec:
  dataSource:
    name: index-mongo-pvc-snapshot-1
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
