apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-mongo
spec:
  replicas: {{ .Values.indexMongo.replicas }}
  selector:
    matchLabels:
      app: index-mongo
  template:
    metadata:
      labels:
        app: index-mongo
    spec:
      containers:
        - name: index-mongo
          image: mongo
          resources:
            requests:
              memory: "256Mi"
              cpu: "16m"
            limits:
              memory: "512Gi"
              cpu: "32m"
