apiVersion: v1
kind: Service
metadata:
  name: murm-logging-es
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: murm-logging-es
  clusterIP: None
  ports:
    - name: rest
      protocol: TCP
      port: 9200
    - name: inter-node
      protocol: TCP
      port: 9300
