{{- $env := .Values.global.env }}
{{- $isDev := eq $env "development" }}

# Only deploy if the environment is not development
{{- if not $isDev }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: murm-logging-es
  namespace: {{ .Values.namespace }}
spec:
  serviceName: murm-logging-es
  replicas: 1
  selector:
    matchLabels:
      app: murm-logging-es
  template:
    metadata:
      labels:
        app: murm-logging-es
    spec:
      containers:
        - name: murm-logging-es
          image: {{ .Values.elasticsearch.image }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.elasticsearch.resources.requests.cpu }}
              memory: {{ .Values.elasticsearch.resources.requests.memory }}
            limits:
              cpu: {{ .Values.elasticsearch.resources.limits.cpu }}
              memory: {{ .Values.elasticsearch.resources.limits.memory }}
          volumeMounts:
            - name: plugins-volume
              mountPath: /usr/share/elasticsearch/plugins
            - name: murm-logging-es-storage
              mountPath: /usr/share/elasticsearch/data
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Setting node name as the pod name for uniqueness
          envFrom:
            - configMapRef:
                name: murm-logging-es-config # ConfigMap with additional environment variables
      initContainers:
        - name: increase-vm-max-map
          image: busybox
          command:
            - sysctl
            - '-w'
            - vm.max_map_count=262144 # Increase vm.max_map_count for Elasticsearch
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command:
            - sh
            - '-c'
            - ulimit -n 65536 # Increase file descriptor limit
          securityContext:
            privileged: true
        - name: file-permissions
          image: busybox:1.32
          command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/'] # Set permissions for Elasticsearch data directory
          volumeMounts:
            - name: murm-logging-es-storage
              mountPath: /usr/share/elasticsearch/data
        - name: install-plugins
          image: {{ .Values.elasticsearch.image }}
          volumeMounts:
          - name: plugins-volume
            mountPath: /usr/share/elasticsearch/plugins
          command:
          - sh
          - -c
          - |
            bin/elasticsearch-plugin remove --purge repository-s3 || true
            bin/elasticsearch-plugin install --batch repository-s3
      volumes:
      - name: plugins-volume
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: murm-logging-es-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: longhorn
      resources:
        requests:
          storage: {{ if eq $env "production" }}10Gi{{ else }}5Gi{{ end }}

{{- end }}
