{{- $env := .Values.global.env }}
{{- $isDev := eq $env "development" }}

# Only deploy if the environment is not development
{{- if not $isDev }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: murm-logging-es
  namespace: {{ .Values.namespace }}
spec:
  serviceName: murm-logging-es
  replicas: 1
  selector:
    matchLabels:
      app: murm-logging-es
  template:
    metadata:
      labels:
        app: murm-logging-es
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      containers:
        - name: murm-logging-es
          image: {{ .Values.elasticsearch.image }}
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: {{ .Values.elasticsearch.resources.requests.cpu }}
              memory: {{ .Values.elasticsearch.resources.requests.memory }}
            limits:
              cpu: {{ .Values.elasticsearch.resources.limits.cpu }}
              memory: {{ .Values.elasticsearch.resources.limits.memory }}
          volumeMounts:
            - name: plugins-volume
              mountPath: /usr/share/elasticsearch/plugins
            - name: murm-logging-es-storage
              mountPath: /usr/share/elasticsearch/data
          ports:
            - containerPort: 9200
              name: rest
              protocol: TCP
            - containerPort: 9300
              name: inter-node
              protocol: TCP
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name # Setting node name as the pod name for uniqueness
          envFrom:
            - configMapRef:
                name: murm-logging-es-config # ConfigMap with additional environment variables
      initContainers:
        - name: increase-vm-max-map
          image: busybox
          command:
            - sysctl
            - '-w'
            - vm.max_map_count=262144 # Increase vm.max_map_count for Elasticsearch
          securityContext:
            privileged: true
        - name: increase-fd-ulimit
          image: busybox
          command:
            - sh
            - '-c'
            - ulimit -n 65536 # Increase file descriptor limit
          securityContext:
            privileged: true
        - name: file-permissions
          image: busybox:1.32
          command: ['chown', '-R', '1000:1000', '/usr/share/elasticsearch/'] # Set permissions for Elasticsearch data directory
          volumeMounts:
            - name: murm-logging-es-storage
              mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: plugins-volume
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: murm-logging-es-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: longhorn
      resources:
        requests:
          storage: 8Gi
{{- end }}
