apiVersion: apps/v1
kind: Deployment
metadata:
  name: murm-logging-kibana
  namespace: {{ .Values.namespace }}
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: murm-logging-kibana
  template:
    metadata:
      labels:
        app: murm-logging-kibana
    spec:
      containers:
        - name: murm-logging-kibana
          image: {{ .Values.kibana.image }}
          resources:
            requests:
              cpu: {{ .Values.kibana.resources.requests.cpu }}
              memory: {{ .Values.kibana.resources.requests.memory }}
            limits:
              cpu: {{ .Values.kibana.resources.limits.cpu }}
              memory: {{ .Values.kibana.resources.limits.memory }}
          ports:
            - containerPort: 5601
          envFrom:
            - configMapRef:
                name: murm-logging-kibana-config
