apiVersion: v1
kind: Service
metadata:
  name: murm-logging-kibana
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: murm-logging-kibana
  ports:
    - name: http
      protocol: TCP
      port: 5601
