apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: murmurations-high-priority
  # Ensure that the PriorityClass is created before other resources in the core chart.
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "-5"
# The value 1000 is relative. It can range from -2147483648 to 2147483647. By default, all pods are set to 0.
value: 1000
globalDefault: false
description: "Use this priority class for high-priority pods."
