apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: index-es-cluster
spec:
  serviceName: index-es
  replicas: 1
  selector:
    matchLabels:
      app: index-es
  template:
    metadata:
      labels:
        app: index-es
    spec:
      containers:
      - name: index-es
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
        ports:
        - containerPort: 9200
          name: rest
          protocol: TCP
        - containerPort: 9300
          name: inter-node
          protocol: TCP
        env:
          - name: cluster.name
            value: index-service-es
          - name: node.name
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: discovery.seed_hosts
            value: "index-es-cluster-0.index-es"
          - name: cluster.initial_master_nodes
            value: "index-es-cluster-0"
          - name: ES_JAVA_OPTS
            value: "-Xms512m -Xmx512m"
      initContainers:
      - name: increase-vm-max-map
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      - name: increase-fd-ulimit
        image: busybox
        command: ["sh", "-c", "ulimit -n 65536"]
        securityContext:
          privileged: true
---
apiVersion: v1
kind: Service
metadata:
  name: index-es
spec:
  selector:
    app: index-es
  # Headless service
  clusterIP: None
  ports:
    - name: rest
      protocol: TCP
      port: 9200
    - name: inter-node
      protocol: TCP
      port: 9300
