apiVersion: apps/v1
kind: Deployment
metadata:
  name: index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
        - name: index
          image: murmurations/index
          # volumeMounts:
          #   - mountPath: /src/index
          #     name: source-code
          env:
            - name: NATS_CLUSTER_ID
              value: murmurations
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MONGO_URI
              value: 'mongodb://index-mongo:27017'
            - name: ELASTICSEARCH_URL
              value: 'http://index-es:9200'
            - name: NATS_URL
              value: 'http://nats:4222'
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
      # volumes:
      #   - name: source-code
      #     hostPath:
      #       path: /Users/max/Desktop/MurmurationsServices
---
apiVersion: v1
kind: Service
metadata:
  name: index
spec:
  selector:
    app: index
  ports:
    - name: index
      protocol: TCP
      port: 8080
