apiVersion: apps/v1
kind: Deployment
metadata:
  name: schemaparser-redis
  labels:
    app: redis
    role: leader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        role: leader
    spec:
      containers:
      - name: leader
        image: redis:6.0.9
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
