apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-kibana
spec:
  # Limit old ReplicaSets to reduce clutter. 0 means only keep the current one.
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: index-kibana
  template:
    metadata:
      labels:
        app: index-kibana
    spec:
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 60
      containers:
        - name: index-kibana
          image: docker.elastic.co/kibana/kibana:7.17.27
          #resources:
          #  requests:
          #    memory: 512Mi
          #    cpu: 100m
          #  limits:
          #    memory: 1024Mi
          #    cpu: 200m
          ports:
            - containerPort: 5601
          envFrom:
            - configMapRef:
                name: index-kibana-config
