apiVersion: apps/v1
kind: Deployment
metadata:
  name: index-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: index-kibana
  template:
    metadata:
      labels:
        app: index-kibana
    spec:
      containers:
        - name: index-kibana
          image: docker.elastic.co/kibana/kibana:7.16.2
          #resources:
          #  requests:
          #    memory: 512Mi
          #    cpu: 100m
          #  limits:
          #    memory: 1024Mi
          #    cpu: 200m
          ports:
            - containerPort: 5601
          envFrom:
            - configMapRef:
                name: index-kibana-config
