name: deploy-core

on:
  push:
    branches:
      - staging
    paths:
      - 'charts/murmdev/charts/core'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 murmdev-k8s

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.4.0'

    - name: Deploy
      run: make helm-murmdev-core
