name: deploy-validation

on:
  push:
    branches:
      - staging
    paths:
      - 'services/common/**'
      - 'services/validation/**'
      - 'charts/murmdev/charts/validation'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish validation docker images
      run: make docker-push-validation

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 murmdev-k8s

    - name: Restart validation deployment
      run: kubectl rollout restart deployment murmurations-validation

    - name: Restart validation deployment
      run: make helm-murmdev-validation
