apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: schemaparser
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: schemaparser
              image: {{ .Values.image }}
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: schemaparser-config
          restartPolicy: Never
