{{- $env := .Values.global.env }}
{{- $isProd := eq $env "production" }}
{{- $isStaging := eq $env "staging" }}
{{- $isPretest := eq $env "pretest" }}
{{- $isDev := eq $env "development" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: geoip-app
spec:
  # Limit old ReplicaSets to reduce clutter. 0 means only keep the current one.
  revisionHistoryLimit: 0
  replicas: {{ .Values.geoip.replicas }}
  selector:
    matchLabels:
      app: geoip-app
  template:
    metadata:
      labels:
        app: geoip-app
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/geoip/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: geoip-app
          image: {{ .Values.image }}
          resources:
            requests:
              memory: "16Mi"
              cpu: "64m"
            limits:
              memory: "32Mi"
              cpu: "128m"
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: geoip-app-config
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 600
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 3
      {{- if $isDev }}
          volumeMounts:
            - mountPath: /src/geoip
              name: source-path
      volumes:
        - name: source-path
          hostPath:
            path: {{ .Values.global.sourcepath }}
      {{- end }}
