apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-app
spec:
  replicas: {{ .Values.validation.replicas }}
  selector:
    matchLabels:
      app: validation-app
  template:
    metadata:
      labels:
        app: validation-app
    spec:
      containers:
        - name: validation-app
          image: {{ .Values.image }}
          # resources:
          #   requests:
          #     memory: "32Mi"
          #     cpu: "8m"
          #   limits:
          #     memory: "64Mi"
          #     cpu: "16m"
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: validation-app-config
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 100
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
      {{- if eq .Values.global.env "development" }}
          volumeMounts:
            - mountPath: /src/validation
              name: source-path
      volumes:
        - name: source-path
          hostPath:
            path: {{ .Values.global.sourcepath }}
      {{- end }}
