{{- $env := .Values.global.env }}
{{- $isLive := eq $env "live" }}
{{- $isLiveTest := eq $env "live-test" }}
{{- $isCI := eq $env "ci" }}
{{- $isDev := eq $env "dev" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-app
spec:
  # Limit old ReplicaSets to reduce clutter. 0 means only keep the current one.
  revisionHistoryLimit: 0
  replicas: {{ .Values.validation.replicas }}
  selector:
    matchLabels:
      app: validation-app
  template:
    metadata:
      labels:
        app: validation-app
        log-group: murm
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/validation/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: validation-app
          image: {{ .Values.image }}
          {{- if $isCI }}
          resources:
            requests:
              memory: "32Mi"
              cpu: "32m"
            limits:
              memory: "64Mi"
              cpu: "64m"
          {{- end }}
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: validation-app-config
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 600
            periodSeconds: 60
            timeoutSeconds: 30
            failureThreshold: 3
      {{- if $isDev }}
          volumeMounts:
            - mountPath: /src/validation
              name: source-path
      volumes:
        - name: source-path
          hostPath:
            path: {{ .Values.global.sourcepath }}
      {{- end }}
