apiVersion: v1
kind: Service
metadata:
  name: validation-app
spec:
  selector:
    app: validation-app
  ports:
    - name: validation
      protocol: TCP
      port: {{ .Values.validation.service.port }}
