apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: index-mongo-pvc
  labels:
    app=index-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: do-block-storage
