apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: profile-mongo-pvc
  labels:
    app: profile-mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
