config:
  cluster:
    enabled: true
    port: 6222
    replicas: 3

  # JetStream configuration for NATS.
  jetstream:
    enabled: true
    fileStore:
      enabled: true
      dir: /data
      pvc:
        enabled: true
        size: 16Mi
        storageClassName:

reloader:
  enabled: false

service:
  name: nats
