config:
  cluster:
    enabled: true
    port: 6222
    replicas: 3

  # JetStream configuration for NATS.
  jetstream:
    enabled: true
    fileStore:
      enabled: true
      pvc:
        enabled: true
        size: 1Gi
        storageClassName: longhorn

reloader:
  enabled: false

service:
  name: nats
