config:
  cluster:
    enabled: true
    port: 6222
    replicas: 3

  # JetStream configuration for NATS.
  jetstream:
    enabled: true
    fileStore:
      enabled: true
      pvc:
        enabled: true
        size: 1Gi
        storageClassName: longhorn

reloader:
  enabled: false

service:
  name: nats

statefulSet:
  patch:
    - op: add
      path: /spec/template/spec/tolerations
      value:
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 60

natsBox:
  podTemplate:
    patch:
      - op: add
        path: /spec/tolerations
        value:
          - key: "node.kubernetes.io/unreachable"
            operator: "Exists"
            effect: "NoExecute"
            tolerationSeconds: 60
          - key: "node.kubernetes.io/not-ready"
            operator: "Exists"
            effect: "NoExecute"
            tolerationSeconds: 60
