apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "murmurations.validation" . }}
spec:
  replicas: {{ .Values.validation.replicas }}
  selector:
    matchLabels:
      app: validation
  template:
    metadata:
      labels:
        app: validation
    spec:
      containers:
        - name: validation
          image: {{ .Values.validationServiceImage }}
          volumeMounts:
            - mountPath: /src/validation
              name: source-path
          env:
            - name: NATS_CLUSTER_ID
              value: murmurations
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: 'http://nats:4222'
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
      volumes:
        - name: source-path
          hostPath:
            path: {{ .Values.sourcepath }}
