apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "murmurations.validation" . }}
spec:
  replicas: {{ .Values.validation.replicas }}
  selector:
    matchLabels:
      app: validation
  template:
    metadata:
      labels:
        app: validation
    spec:
      containers:
        - name: validation
          image: {{ .Values.validationServiceImage }}
          volumeMounts:
            - mountPath: /src/validation
              name: source-path
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
            failureThreshold: 3
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
            - configMapRef:
                name: validation-config
      volumes:
        - name: source-path
          hostPath:
            path: {{ .Values.sourcepath }}
