apiVersion: v1
kind: Service
metadata:
  name: {{ template "murmurations.validation" . }}
spec:
  selector:
    app: validation
  ports:
    - name: validation
      protocol: TCP
      port: {{ .Values.validation.service.port }}
