name: deploy-nodecleaner

on:
  push:
    branches:
      - staging
    paths:
      - 'services/common/**'
      - 'services/nodecleaner/**'
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Publish nodecleaner docker images
      run: make docker-push-nodecleaner
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save murmdev-k8s
    - name: Restart nodecleaner deployment
      run: kubectl rollout restart deployment murmurations-nodecleaner
