name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Execute Tests
        run: make test

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21
      - name: Run Linter
        uses: golangci/golangci-lint-action@v4

  build:
    name: Build Docker Image - ${{ matrix.service }}
    needs:
      - test
      - lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - index
          - library
          - validation
          - dataproxy
          - nodecleaner
          - revalidatenode
          - schemaparser
          - dataproxyupdater
          - dataproxyrefresher
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: DockerHub Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Publish Docker Image
        run: make docker-push-${{ matrix.service }} DEPLOY_ENV=production

  deploy:
    name: Deploy Services
    needs:
      - test
      - lint
      - build
    runs-on: ubuntu-latest
    env:
      SERVER_IP: ${{ secrets.PRODUCTION_SERVER_IP }}
      KUBECONFIG_PATH: ${{ secrets.KUBECONFIG_PATH }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DEPLOY_ENV: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup SSH and Deploy Services
        run: ./scripts/deploy-services.sh
