# This workflow defines two jobs that run tests and linting for a Go project
# when a pull request is opened or updated on the main branch. By using GitHub
# Actions, the project can automatically run tests and linting on every pull
# request, which helps ensure that the code is high quality and free of errors.

name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19.5
      - run: make test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19.5
      - uses: golangci/golangci-lint-action@v3
