# Workflow Description:
# This GitHub Actions workflow is initiated by specific review comments from
# authorized users in pull request reviews. It automates the build and deployment
# process when a comment containing '/rebuild' is detected.

name: Redeploy on Specific Review Comment by Authorized User

# Triggers:
# The workflow is activated by the creation of review comments in pull requests.
on:
  pull_request_review_comment:
    types: [created]

jobs:
  # Job: Check Comment and Trigger Build
  # This job checks if the comment contains '/rebuild'. It triggers the subsequent
  # build job only if this condition is met.
  check-comment-and-trigger-build:
    if: contains(github.event.comment.body, '/rebuild')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Build Job
        run: echo "Triggering Build Job"

  # Job: Build Docker Image
  build:
    name: Build Docker Image - ${{ matrix.service }}
    needs: check-comment-and-trigger-build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - index
          - library
          - geoip
          - validation
          - dataproxy
          - nodecleaner
          - revalidatenode
          - schemaparser
          - dataproxyupdater
          - dataproxyrefresher

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Check out the PR's head branch.

      - name: DockerHub Login
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish Docker Image
        run: make docker-push-${{ matrix.service }} DEPLOY_ENV=pretest

  # Job: Deploy Services
  deploy:
    name: Deploy Services
    needs: build
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: pretest
      PRETEST_SERVER_IP: ${{ secrets.PRETEST_SERVER_IP }}
      PRETEST_KUBECONFIG_PATH: ${{ secrets.PRETEST_KUBECONFIG_PATH }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }} # Check out the PR's head branch.

      - name: Run Deployment Script
        run: ./scripts/deploy-services.sh

  e2e_test:
    name: E2E Test
    needs:
      - test
      - lint
      - check-exclusions
      - build
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Newman
        run: |
          npm install -g newman

      - name: Test Index
        run: >
          ./scripts/wait_for_timeout.sh
          https://pretest1-index.murmurations.network/v2/ping 200 300

      - name: Test Library
        run: >
          ./scripts/wait_for_timeout.sh
          https://pretest1-library.murmurations.network/v2/ping 200 300

      - name: Test Data Proxy
        run: >
          ./scripts/wait_for_timeout.sh
          https://pretest1-data-proxy.murmurations.network/v1/ping 200 300

      - name: Newman E2E Test
        run: make newman-test DEPLOY_ENV=pretest
