name: staging-library

on:
  push:
    branches:
      - staging
    paths:
      - 'common/**'
      - 'services/library/**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Test
      run: make test

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Login to DockerHub
      uses: docker/login-action@v1.10.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Publish library docker images
      run: make docker-push-library

  deploy:
    name: Deploy
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4

    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 1200 murmtest

    - name: Restart library deployment
      run: make deploy-library
