name: CICD

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    - name: Test
      run: make test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build the index image
      run: make index
    - name: Publish the index image
      run: make publish-index

    - name: Build the validation image
      run: make validation
    - name: Publish the validation image
      run: make publish-validation

    - name: Build the library image
      run: make library
    - name: Publish the library image
      run: make publish-library

    - name: Build the nodecleanup image
      run: make nodecleanup
    - name: Publish the nodecleanup image
      run: make publish-nodecleanup

    - name: Build the parseschema image
      run: make parseschema
    - name: Publish the parseschema image
      run: make publish-parseschema
