name: test

on:
  push:
    branches:
      - main
      - staging
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
    - name: Test
      run: make test
